version: '3.9'
services:
  db:
    image: mysql:8.0.34
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Lisbon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: popcornblog
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - movies-network
  movies:
    image: alfeups/movies
    restart: always
    build: ./movies
    working_dir: /movies
    environment:
      TZ: Europe/Lisbon
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/popcornblog?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - movies-network
networks:
  movies-network:
    driver: bridge