server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/popcornblog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.validation: DEBUG
    javax.validation: DEBUG
